version: '3'

services:
  database:
    container_name: postgresql_db
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hwibsaki
      - POSTGRES_USER=hwibaski
      - POSTGRES_PASSWORD=hwibaski
      - TZ=Asia/Seoul
    ports:
      - '5432:5432'
